name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
           node-version: 16
    - name: Install dependencies
      run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile --legacy-peer-deps
          elif [ -e package-lock.json ]; then
          npm ci --legacy-peer-deps
          else
          npm i --legacy-peer-deps
          fi
    - run: npm run docs:build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
          deploy_key: ${{ secrets.yangyuanchao }}
          publish_dir: docs-dist
          publish_branch: pages
          commit_message: ${{ github.event.head_commit.message }}
